CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `username` VARCHAR(20) NULL COMMENT '用户名',
  `nickname` VARCHAR(50) NULL COMMENT '昵称',
  `avatar_url` VARCHAR(255) NULL COMMENT '头像地址',
  `email` VARCHAR(128) NULL COMMENT '邮箱',
  `email_verified_at` DATETIME NULL COMMENT '邮箱验证时间',
  `phone` VARCHAR(20) NULL COMMENT '手机号',
  `phone_verified_at` DATETIME NULL COMMENT '手机号验证时间',
  `password_hash` VARCHAR(255) NULL COMMENT '密码哈希',
  `password_updated_at` DATETIME NULL COMMENT '密码最近更新时间',
  `registration_source` ENUM('app', 'web') NOT NULL COMMENT '注册来源',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `failed_login_count` INT NOT NULL DEFAULT 0 COMMENT '连续登录失败次数',
  `locked_until` DATETIME NULL COMMENT '锁定截止时间',
  `last_login_at` DATETIME NULL COMMENT '最后登录时间',
  `deleted_at` DATETIME NULL COMMENT '软删除时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_users_username` (`username`),
  UNIQUE KEY `uk_users_email` (`email`),
  UNIQUE KEY `uk_users_phone` (`phone`),
  KEY `idx_users_registration_source` (`registration_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';
